// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/stream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StreamDemo_Ping_FullMethodName           = "/stream.StreamDemo/Ping"
	StreamDemo_CountDown_FullMethodName      = "/stream.StreamDemo/CountDown"
	StreamDemo_ComputeAverage_FullMethodName = "/stream.StreamDemo/ComputeAverage"
	StreamDemo_LiveChat_FullMethodName       = "/stream.StreamDemo/LiveChat"
)

// StreamDemoClient is the client API for StreamDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamDemoClient interface {
	// 1. 一元调用
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// 2. 服务端流
	CountDown(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CountResponse], error)
	// 3. 客户端流
	ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NumberRequest, AverageResponse], error)
	// 4. 双向流
	LiveChat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatRequest, ChatResponse], error)
}

type streamDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamDemoClient(cc grpc.ClientConnInterface) StreamDemoClient {
	return &streamDemoClient{cc}
}

func (c *streamDemoClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, StreamDemo_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *streamDemoClient) CountDown(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CountResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamDemo_ServiceDesc.Streams[0], StreamDemo_CountDown_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CountRequest, CountResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamDemo_CountDownClient = grpc.ServerStreamingClient[CountResponse]

func (c *streamDemoClient) ComputeAverage(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[NumberRequest, AverageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamDemo_ServiceDesc.Streams[1], StreamDemo_ComputeAverage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NumberRequest, AverageResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamDemo_ComputeAverageClient = grpc.ClientStreamingClient[NumberRequest, AverageResponse]

func (c *streamDemoClient) LiveChat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatRequest, ChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StreamDemo_ServiceDesc.Streams[2], StreamDemo_LiveChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamDemo_LiveChatClient = grpc.BidiStreamingClient[ChatRequest, ChatResponse]

// StreamDemoServer is the server API for StreamDemo service.
// All implementations must embed UnimplementedStreamDemoServer
// for forward compatibility.
type StreamDemoServer interface {
	// 1. 一元调用
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// 2. 服务端流
	CountDown(*CountRequest, grpc.ServerStreamingServer[CountResponse]) error
	// 3. 客户端流
	ComputeAverage(grpc.ClientStreamingServer[NumberRequest, AverageResponse]) error
	// 4. 双向流
	LiveChat(grpc.BidiStreamingServer[ChatRequest, ChatResponse]) error
	mustEmbedUnimplementedStreamDemoServer()
}

// UnimplementedStreamDemoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStreamDemoServer struct{}

func (UnimplementedStreamDemoServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedStreamDemoServer) CountDown(*CountRequest, grpc.ServerStreamingServer[CountResponse]) error {
	return status.Error(codes.Unimplemented, "method CountDown not implemented")
}
func (UnimplementedStreamDemoServer) ComputeAverage(grpc.ClientStreamingServer[NumberRequest, AverageResponse]) error {
	return status.Error(codes.Unimplemented, "method ComputeAverage not implemented")
}
func (UnimplementedStreamDemoServer) LiveChat(grpc.BidiStreamingServer[ChatRequest, ChatResponse]) error {
	return status.Error(codes.Unimplemented, "method LiveChat not implemented")
}
func (UnimplementedStreamDemoServer) mustEmbedUnimplementedStreamDemoServer() {}
func (UnimplementedStreamDemoServer) testEmbeddedByValue()                    {}

// UnsafeStreamDemoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamDemoServer will
// result in compilation errors.
type UnsafeStreamDemoServer interface {
	mustEmbedUnimplementedStreamDemoServer()
}

func RegisterStreamDemoServer(s grpc.ServiceRegistrar, srv StreamDemoServer) {
	// If the following call panics, it indicates UnimplementedStreamDemoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StreamDemo_ServiceDesc, srv)
}

func _StreamDemo_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StreamDemoServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StreamDemo_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StreamDemoServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StreamDemo_CountDown_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CountRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamDemoServer).CountDown(m, &grpc.GenericServerStream[CountRequest, CountResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamDemo_CountDownServer = grpc.ServerStreamingServer[CountResponse]

func _StreamDemo_ComputeAverage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamDemoServer).ComputeAverage(&grpc.GenericServerStream[NumberRequest, AverageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamDemo_ComputeAverageServer = grpc.ClientStreamingServer[NumberRequest, AverageResponse]

func _StreamDemo_LiveChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamDemoServer).LiveChat(&grpc.GenericServerStream[ChatRequest, ChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StreamDemo_LiveChatServer = grpc.BidiStreamingServer[ChatRequest, ChatResponse]

// StreamDemo_ServiceDesc is the grpc.ServiceDesc for StreamDemo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StreamDemo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stream.StreamDemo",
	HandlerType: (*StreamDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _StreamDemo_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CountDown",
			Handler:       _StreamDemo_CountDown_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ComputeAverage",
			Handler:       _StreamDemo_ComputeAverage_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "LiveChat",
			Handler:       _StreamDemo_LiveChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/stream.proto",
}
